version: "3.8"
services:
  client:
    stdin_open: true
    build:
      context: "./client/"
      dockerfile: Dockerfile-client
    ports:
      - "3000:3000"
  backend:
    build:
      context: "./backend"
      dockerfile: Dockerfile-backend
    ports:
      - "8080:8080"