name: Hostem Management

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push React client Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: ./client/Dockerfile-client
          push: true
          tags: 1bm21cs043/hostel_management:latest

      - name: Build and push Node.js backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile-backend
          push: true
          tags: 1bm21cs043/hostel_management:latest
